### ISSUE TITLE
How to deploy it in netlify?

### ISSUE THREAD

**Issue by LoopGlitch26** [hermanzdosilovic/online-compiler#3]
Can you provide steps to follow for deployment

**Comment by hermanzdosilovic** [comment]
1. Fork this repository.
2. Choose a plan on https://judge0.com/ce (FREE plan is available).
3. Add your RapidAPI key [here](https://github.com/hermanzdosilovic/online-compiler/blob/master/index.html#L55).
4. [Follow this tutorial](https://www.netlify.com/blog/2016/09/29/a-step-by-step-guide-deploying-on-netlify).

**Comment by LoopGlitch26** [comment]
But simply deployment will not do the API calls, right? We need netlify lambda functions or aws lambda or something..can you please check and let me know.

**Comment by hermanzdosilovic** [comment]
If you follow the above steps it will work just as https://online-compiler.dosilovic.com works.

**Comment by LoopGlitch26** [comment]
Thank you.
